[package]
name = "drv-dac-server"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = { workspace = true }
cortex-m = { workspace = true }
idol-runtime = { workspace = true }
num-traits = { workspace = true }
stm32h7 = { workspace = true }
zerocopy = { workspace = true }

drv-dac-api = { path = "../dac-api" }
#drv-dac = { path = "../dac", optional = true }
# drv-stm32h7-hash = { path = "../stm32h7-hash", optional = true }
# drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api", features = ["family-stm32h7"] }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[build-dependencies]
build-util = { path = "../../build/util" }
idol = { workspace = true }

[features]
h753 = ["stm32h7/stm32h753", "drv-stm32xx-sys-api/h753"]

no-ipc-counters = ["idol/no-counters"]

[[bin]]
name = "drv-dac-server"
test = false
doctest = false
bench = false

[lints]
workspace = true
